### ISSUE TITLE
Capturing stderr

### ISSUE THREAD

**Issue by domenkozar** [Tehnix/ide-haskell-hie#13]
Currently there's no capture of stderr in the plugin, which may be crucial information if something went really bad.

**Comment by Tehnix** [comment]
@domenkozar there's none when enabling debug logging for HIE, but if you enable the setting `Debug L S P` under Settings -> Core, then you can view stderr messages in the developer console.

IMO that should suffice for now, but I'd of course welcome a PR for adding stderr.

I'll close this to clean the issues a bit, but I'm all for reopening if it's not a satisfactory solution :)
