### ISSUE TITLE
Duplicate information on hover

### ISSUE THREAD

**Issue by falsandtru** [Tehnix/ide-haskell-hie#15]
When I disable and enable again this plugin, this plugin displays duplicate info on hover.

**Comment by Tehnix** [comment]
Hmm, I'd say that's quite an edge case I'm not sure is worth doing any significant work for; a `CMD + SHIFT + P -> Window Reload` should fix the issues. I'd of course welcome a PR for this if anyone wants to implement it.

I'll close this, but let me know if this is a serious issue for you. I can't currently imagine any workflow that would require the plugin to be disabled and then enabled again.

**Comment by falsandtru** [comment]
As a workaround, I'm using this workflow to reload and apply some settings such as `.cabal` and `.hlint.yaml`. Is there any better ways?

**Comment by Tehnix** [comment]
I would suggest doing the window reload instead, but it might actually be worth adding a restart command to the HIE process. That said, I think this is originally intended that hie/ghc-mod would notice these changes, but from personal experience, they rarely take effect until a reload.

**Comment by falsandtru** [comment]
Thanks, I'll use it.

**Comment by Tehnix** [comment]
@falsandtru I've just updated the plugin with a restart command, so now you can restart it from the command palette :)

I'll close this, but let me know if that doesn't solve your issue.
