### ISSUE TITLE
Last update broke the package

### ISSUE THREAD

**Issue by LukaHorvat** [Tehnix/ide-haskell-hie#19]
Updated to 0.10.0 and it just doesn't work anymore. hie no longer starts up, the console logs don't show anything and restarting the server just gives me a "HIE restarted and currently initializing" message and an infinite spinner.

```
> hie --version
Version 0.1.0.0, Git revision 54338553f9c07b7d3427a769f7f4c2c366cefc7f (dirty) (1218 commits) x86_64 ghc-8.2.2

> atom --version

Atom    : 1.25.0-beta3
Electron: 1.7.11
Chrome  : 58.0.3029.110
Node    : 7.9.0
```

I'm running Windows 10.

**Comment by LukaHorvat** [comment]
So I've installed the 0.9.1 version now and I still can't get it working. Very weird since it was working yesterday and I didn't change anything.

**Comment by LukaHorvat** [comment]
Ok, I don't know what exactly happened but it seems to be working now. hie still doesn't start by itself but it does when I explicitly invoke the restart command.

**Comment by Tehnix** [comment]
Hmm, testing it locally I had the same issue from the earlier version that used to work, and thought my problem was entirely local (0.10.0 didn't really change anything except adding a command).

It feels like Atom is no longer automatically starting the language client. I'll see if it solves it by moving the dependency around a bit.

**Comment by Tehnix** [comment]
I have opened a ticket on `atom-languageclient` with some questions that'll hopefully get me to the bottom of this https://github.com/atom/atom-languageclient/issues/195.

**Comment by Tehnix** [comment]
Issue has been resolved in the newest update! Apparently I completely misinterpreted the usage of activationCommands, in my rush to implement restart functionality.

Sorry for the inconvenience!!
