### ISSUE TITLE
Error appears twice

### ISSUE THREAD

**Issue by freeman42x** [Tehnix/ide-haskell-hie#24]
To reproduce take any compiling code and put a hole in it using `_` for example.

Almost immediately errors will be seen under Errors tab:

    /home/neo/Forks/fp-course/src/Course/Applicative.hs: 371, 42
    • Found hole: _ :: Bool -> List a -> List a
      Where: ‘a’ is a rigid type variable bound by
               the type signature for:
                 filtering :: forall (f :: * -> *) a.
                              Applicative f =>
                              (a -> f Bool) -> List a -> f (List a)
               at /home/neo/Forks/fp-course/src/Course/Applicative.hs:(366,1)-(370,15)
    • In the first argument of ‘lift2’, namely ‘_’
      In the expression: lift2 _ (f a) acc
      In the first argument of ‘foldRight’, namely
        ‘(\ a acc -> lift2 _ (f a) acc)’
    • Relevant bindings include
        acc :: f (List a)
          (bound at /home/neo/Forks/fp-course/src/Course/Applicative.hs:371:29)
        a :: a
          (bound at /home/neo/Forks/fp-course/src/Course/Applicative.hs:371:27)
        f :: a -> f Bool
          (bound at /home/neo/Forks/fp-course/src/Course/Applicative.hs:371:11)
        filtering :: (a -> f Bool) -> List a -> f (List a)
          (bound at /home/neo/Forks/fp-course/src/Course/Applicative.hs:371:1)

After a while (3-5 seconds) the same error with small differences will appear again under the first error:

    /home/neo/Forks/fp-course/src/Course/Applicative.hs: 371, 42
    • Found hole: _ :: Bool -> List a -> List a
      Where: ‘a’ is a rigid type variable bound by
               the type signature for:
                 filtering :: forall (f :: * -> *) a.
                              Applicative f =>
                              (a -> f Bool) -> List a -> f (List a)
               at src/Course/Applicative.hs:(366,1)-(370,15)
    • In the first argument of ‘lift2’, namely ‘_’
      In the expression: lift2 _ (f a) acc
      In the first argument of ‘foldRight’, namely
        ‘(\ a acc -> lift2 _ (f a) acc)’
    • Relevant bindings include
        acc :: f (List a) (bound at src/Course/Applicative.hs:371:29)
        a :: a (bound at src/Course/Applicative.hs:371:27)
        f :: a -> f Bool (bound at src/Course/Applicative.hs:371:11)
        filtering :: (a -> f Bool) -> List a -> f (List a)
          (bound at src/Course/Applicative.hs:371:1)

**Comment by Tehnix** [comment]
Hi @razvan-panda !

Sorry for not responding earlier. Is this still a problem with the latest version of HIE and atom-ide-ui?

**Comment by freeman42x** [comment]
I can no longer reproduce the issue on 0.10.1

**Comment by Tehnix** [comment]
Thanks for testing again! I'll close this then :)
