### ISSUE TITLE
Feature Request - Make error warning pop up dialogue copy-able

### ISSUE THREAD

**Issue by theGhostJW** [Tehnix/ide-haskell-hie#26]
When you have over an error or hint you can select the text but not copy it.
It would be useful if copying could be enabled.

**Comment by Tehnix** [comment]
UI things all come from [atom-ide-ui](https://github.com/facebook-atom/atom-ide-ui). I think these issues might be related:

- https://github.com/facebook-atom/atom-ide-ui/issues/283
- https://github.com/facebook-atom/atom-ide-ui/issues/182
- https://github.com/facebook-atom/atom-ide-ui/issues/81

Although not much feedback on them :/

NOTE: I know this seems like I'm just throwing the problem to someone else, even though your feature requests are great! :) But the thing is, with the LSP model, responsibilities are sorta spread out a couple of places, to avoid duplication. 

Namely: UI is the editors LSP client package, features is the languages LSP server package, and this extension is really just instructions to Atom on how to launch the LSP server.

**Comment by theGhostJW** [comment]
OK in that case will close both tomorrow unless for some reason you want them open ?? (e.g. so someone else doesn't log the same thing)

**Comment by Tehnix** [comment]
I think it's fine to close them, people can still search the closed ones :)
