### ISSUE TITLE
Feature Request - Insert Type

### ISSUE THREAD

**Issue by theGhostJW** [Tehnix/ide-haskell-hie#27]
It would be great to be able to click on a warning / error and insert a type signature

**Comment by Tehnix** [comment]
Insert type will eventually come via haskell-ide-engine (https://github.com/haskell/haskell-ide-engine#planned-features), since this is really just a thin wrapper around the LSP.

There is already the type information on hover though, was that the one you were thinking of inserting?

**Comment by theGhostJW** [comment]
Yes that would be the one. With -warn-missing-signatures and -Werror it comes up as an error (including the type info), but I notice the type info still comes up on hover so that would work.

Just to clarify - as this is purely dependent on haskel-ide-engine should I close it?

**Comment by Tehnix** [comment]
Inserting the type info that is displayed on hover would be at haskell-ide-engine, but being able to insert something from the generic warnings/error pop-ups would probably be atom-ide-ui's responsibility.

In any case, I'll close this, but do feel free to make tickets on the other two referring to this one if you want! :)

And thanks for being so understanding! :)
