### ISSUE TITLE
Using ide-haskell-hie when haskell-ide-engine is installed through Stack

### ISSUE THREAD

**Issue by rossng** [Tehnix/ide-haskell-hie#29]
On Windows, I installed `haskell-ide-engine` by cloning the repo and running `stack install`. However, Stack does not provide a version of GHC on the `PATH` and I do not have Haskell Platform or GHC installed globally (nor do I want to). Hence `haskell-ide-engine` crashes if it is run outside Stack.

The only way I can get `ide-haskell-hie` to work is by running `stack exec atom`. Is Stack officially supported by this project (or could I add it?)

**Comment by jkachmar** [comment]
It looks like 2657d54 should address this so long as you're using the provided `hie-wrapper.sh` script.

Perhaps @Tehnix or @lexi-lambda confirm this?

**Comment by Tehnix** [comment]
I'll assume this was fixed by the updated wrapper. If not, we can reopen the issue :)
