### ISSUE TITLE
HIE and Atom

### ISSUE THREAD

**Issue by Bendodroid** [Tehnix/ide-haskell-hie#33]
I installed HIE with stack and the atom plugin ide-haskell-hie and the only change so far is that HIE initializes forever (little circle in the status bar) and I no longer have autocompletion.

How is this supposed to work?

**Comment by colbyn** [comment]
Hey @Bendodroid  if it helps.  I installed HIE via the `make build-all` command. After installing `ide-haskell-hie` I clicked on the ‘Use the hie-wrapper’ button and restarted Atom, and thereafter everything (including autocomplete) seems to be working…

**Comment by Tehnix** [comment]
I'll close this as a duplicate of https://github.com/Tehnix/ide-haskell-hie/issues/34 (keeping that one because it had a more descriptive title).

Usually the core issue is that the HIE version does not match your project.
