### ISSUE TITLE
Stuck in loop: "hie initializing for Haskell"

### ISSUE THREAD

**Issue by freeman42x** [Tehnix/ide-haskell-hie#34]
When Atom is started and a Haskell code file is loaded the spinner at the bottom `hie initializing for Haskell` keeps going on forever.

The following errors/warnings are shown in Atom console:

> C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\logger.js:12 Haskell (hie) Array(1)0: Array(2)0: "rpc.onError"1: Array(3)0: Error: write EPIPE
>     at _errnoException (util.js:1024:11)
>     at Socket._writeGeneric (net.js:767:25)
>     at Socket._write (net.js:786:8)
>     at doWrite (_stream_writable.js:387:12)
>     at writeOrBuffer (_stream_writable.js:373:5)
>     at Socket.Writable.write (_stream_writable.js:290:11)
>     at Socket.write (net.js:704:40)
>     at StreamMessageWriter.write (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\vscode-jsonrpc\lib\messageWriter.js:69:27)
>     at Promise (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\vscode-jsonrpc\lib\main.js:810:35)
>     at new Promise (<anonymous>)
>     at Object.sendRequest (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\vscode-jsonrpc\lib\main.js:800:26)
>     at LanguageClientConnection.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:379:46)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:3:12)
>     at LanguageClientConnection._sendRequest (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:367:16)
>     at LanguageClientConnection.initialize (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:57:21)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:260:47)
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:4:58)
>     at <anonymous>code: "EPIPE"errno: "EPIPE"rawStack: (22) [CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite]0: CallSite__proto__: constructor: ƒ CallSite()getColumnNumber: ƒ getColumnNumber()getEvalOrigin: ƒ getEvalOrigin()getFileName: ƒ getFileName()getFunction: ƒ getFunction()getFunctionName: ƒ getFunctionName()getLineNumber: ƒ getLineNumber()getMethodName: ƒ getMethodName()getPosition: ƒ getPosition()getScriptNameOrSourceURL: ƒ getScriptNameOrSourceURL()getThis: ƒ getThis()getTypeName: ƒ getTypeName()isConstructor: ƒ isConstructor()isEval: ƒ isEval()isNative: ƒ isNative()isToplevel: ƒ isToplevel()toString: ƒ toString()__proto__: Object1: CallSite {}2: CallSite {}3: CallSite {}4: CallSite {}5: CallSite {}6: CallSite {}7: CallSite {}8: CallSite {}9: CallSite {}10: CallSite {}11: CallSite {}12: CallSite {}13: CallSite {}14: CallSite {}15: CallSite {}16: CallSite {}17: CallSite {}18: CallSite {}19: CallSite {}20: CallSite {}21: CallSite {}length: 22__proto__: Array(0)syscall: "write"message: "write EPIPE"stack: "Error: write EPIPE↵    at _errnoException (util.js:1024:11)↵    at Socket._writeGeneric (net.js:767:25)↵    at Socket._write (net.js:786:8)↵    at doWrite (_stream_writable.js:387:12)↵    at writeOrBuffer (_stream_writable.js:373:5)↵    at Socket.Writable.write (_stream_writable.js:290:11)↵    at Socket.write (net.js:704:40)↵    at StreamMessageWriter.write (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\vscode-jsonrpc\lib\messageWriter.js:69:27)↵    at Promise (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\vscode-jsonrpc\lib\main.js:810:35)↵    at new Promise (<anonymous>)↵    at Object.sendRequest (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\vscode-jsonrpc\lib\main.js:800:26)↵    at LanguageClientConnection.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:379:46)↵    at Generator.next (<anonymous>)↵    at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:7:71↵    at new Promise (<anonymous>)↵    at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:3:12)↵    at LanguageClientConnection._sendRequest (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:367:16)↵    at LanguageClientConnection.initialize (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:57:21)↵    at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:260:47)↵    at Generator.next (<anonymous>)↵    at fulfilled (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:4:58)↵    at <anonymous>"__proto__: Object1: undefined2: undefinedlength: 3__proto__: Array(0)length: 2__proto__: Array(0)length: 1__proto__: Array(0)
> error @ C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\logger.js:12
> C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\logger.js:12 Haskell (hie) Array(1)0: Array(2)0: "rpc.onError"1: Array(3)0: Error: This socket is closed
>     at Socket._writeGeneric (net.js:726:18)
>     at Socket._write (net.js:786:8)
>     at doWrite (_stream_writable.js:387:12)
>     at writeOrBuffer (_stream_writable.js:373:5)
>     at Socket.Writable.write (_stream_writable.js:290:11)
>     at Socket.write (net.js:704:40)
>     at StreamMessageWriter.write (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\vscode-jsonrpc\lib\messageWriter.js:71:27)
>     at Promise (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\vscode-jsonrpc\lib\main.js:810:35)
>     at new Promise (<anonymous>)
>     at Object.sendRequest (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\vscode-jsonrpc\lib\main.js:800:26)
>     at LanguageClientConnection.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:379:46)
>     at Generator.next (<anonymous>)
>     at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:7:71
>     at new Promise (<anonymous>)
>     at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:3:12)
>     at LanguageClientConnection._sendRequest (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:367:16)
>     at LanguageClientConnection.initialize (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:57:21)
>     at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:260:47)
>     at Generator.next (<anonymous>)
>     at fulfilled (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:4:58)
>     at <anonymous>rawStack: (21) [CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite, CallSite]message: "This socket is closed"stack: "Error: This socket is closed↵    at Socket._writeGeneric (net.js:726:18)↵    at Socket._write (net.js:786:8)↵    at doWrite (_stream_writable.js:387:12)↵    at writeOrBuffer (_stream_writable.js:373:5)↵    at Socket.Writable.write (_stream_writable.js:290:11)↵    at Socket.write (net.js:704:40)↵    at StreamMessageWriter.write (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\vscode-jsonrpc\lib\messageWriter.js:71:27)↵    at Promise (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\vscode-jsonrpc\lib\main.js:810:35)↵    at new Promise (<anonymous>)↵    at Object.sendRequest (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\vscode-jsonrpc\lib\main.js:800:26)↵    at LanguageClientConnection.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:379:46)↵    at Generator.next (<anonymous>)↵    at C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:7:71↵    at new Promise (<anonymous>)↵    at __awaiter (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:3:12)↵    at LanguageClientConnection._sendRequest (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:367:16)↵    at LanguageClientConnection.initialize (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\languageclient.js:57:21)↵    at HaskellLanguageClient.<anonymous> (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:260:47)↵    at Generator.next (<anonymous>)↵    at fulfilled (C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\auto-languageclient.js:4:58)↵    at <anonymous>"__proto__: Object1: undefined2: undefinedlength: 3__proto__: Array(0)length: 2__proto__: Array(0)length: 1__proto__: Array(0)
> error @ C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\logger.js:12
> C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\logger.js:9 Haskell (hie) stderr 'ghc' is not recognized as an internal or external command,
> warn @ C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\logger.js:9
> C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\logger.js:9 Haskell (hie) stderr operable program or batch file.
> warn @ C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\logger.js:9
> C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\logger.js:9 Haskell (hie) stderr hie: readCreateProcess: ghc --numeric-version (exit 1): failed
> warn @ C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\logger.js:9
> C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\logger.js:9 Haskell (hie) rpc.onClose The RPC connection closed unexpectedly
> warn @ C:\Users\Razvan\.atom\packages\ide-haskell-hie\node_modules\atom-languageclient\build\lib\logger.js:9

Using HIE:

> Version 0.4.0.1, Git revision 7e0b19721872d1c8e44f49484ac75f6c61412349 (2220 commits) x86_64 ghc-8.2.2

**Comment by freeman42x** [comment]
My issue might be caused by: https://github.com/haskell/cabal/issues/5780 Will report back once I figure it out.

**Comment by Tehnix** [comment]
Usually these issues pop-up when the HIE version does not match the GHC version of the project.

I'm doing some clean-up in the issues. If this is still a problem, please let me know and I'll reopen this issue :)
