### ISSUE TITLE
Uncaught Error: Header must provide a Content-Length property.

### ISSUE THREAD

**Issue by emdash-ie** [Tehnix/ide-haskell-hie#37]
I’m not really sure where this issue should go. Atom claims the error is being thrown in this package, but I uninstalled the package several days ago (to get rid of this error). Restarting Atom gets rid of the errors for a while (sometimes a few hours), but they eventually come back.

With the mention of sockets in the trace, I’m wondering if there are messages somehow left in the socket from when the package was installed that are only being read now? That seems odd given it’s been about a week since I uninstalled the package (I’m surprised something like that would persist through a reboot).

Any direction would be appreciated – I can move this to atom core, or to atom-ide-ui, if it might be better in either place.

**Atom**: 1.34.0 x64
**Electron**: 2.0.16
**OS**: Mac OS X 10.14.2
**Thrown From**: 'ide-haskell-hie' package vundefined

### Stack Trace

Uncaught Error: Header must provide a Content-Length property.

```
At /Users/Noel/.atom/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/messageReader.js:163

Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/messageReader.js:163:27)
    at Socket.readable.on (/packages/ide-haskell-hie/node_modules/vscode-jsonrpc/lib/messageReader.js:148:18)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:594:20)
```

### Commands

```
     -0:57.4.0 vim-mode-plus:join (input.hidden-input)
     -0:57.1.0 vim-mode-plus:delete-right (input.hidden-input)
  2x -0:56.8.0 vim-mode-plus:join (input.hidden-input)
     -0:55.4.0 vim-mode-plus:delete-right (input.hidden-input)
     -0:54.1.0 vim-mode-plus:reset-normal-mode (input.hidden-input)
     -0:53.7.0 core:save (input.hidden-input)
     -0:50.4.0 vim-mode-plus:move-down (input.hidden-input)
  2x -0:50 vim-mode-plus:delete (input.hidden-input)
     -0:49.7.0 core:save (input.hidden-input)
     -0:48.8.0 vim-mode-plus:insert-after-end-of-line (input.hidden-input)
  3x -0:48.4.0 core:backspace (input.hidden-input)
     -0:45.5.0 vim-mode-plus:activate-normal-mode (input.hidden-input)
     -0:45.1.0 core:save (input.hidden-input)
     -0:38.3.0 fuzzy-finder:toggle-file-finder (input.hidden-input)
     -0:37.4.0 core:confirm (input.hidden-input)
     -0:34.6.0 tree-view:toggle (input.hidden-input)
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
atom-material-syntax-light 0.4.6 
autocomplete-python 1.11.0 
build 0.70.0 
busy-signal 2.0.0 
choose-pane 0.8.0 
copy-file-contents 0.3.0 
direction 0.0.0 
docblockr 0.13.7 
editor-settings 1.1.3 
file-icons 2.1.27 
haskell-pointfree 0.2.0 
Hydrogen 2.7.0 
ide-python 1.2.0 
ide-scala 0.8.2 
intentions 1.1.5 
jslint 1.5.1 
keystroke 0.4.0 
language-arduino 0.4.3 
language-babel 2.85.0 
language-elm 1.5.0 
language-emacs-lisp 1.3.0 
language-fish-shell 1.1.0 
language-gradle 0.1.0 
language-groovy 0.7.0 
language-haskell 1.18.0 
language-jflex 1.0.0 
language-latex 1.2.0 
language-lisp 0.2.0 
language-markdown 0.28.0 
language-pfm 0.82.0 
language-restructuredtext 1.1.2 
language-scala 1.1.9 
language-scheme 1.4.0 
language-systemd 0.1.1 
language-x86-64-assembly 2.2.11 
linter 2.2.0 
linter-gcc 0.7.1 
linter-javac 1.9.4 
linter-mypy 2.6.2 
linter-ui-default 1.7.1 
long-lines 0.0.0 
mark-long-lines 0.0.0 
markdown-preview-enhanced 0.15.8 
markdown-table-editor 1.1.1 
open-terminal-here 2.3.2 
pandoc-table-editor 0.0.0 
platformio-ide-terminal 2.8.4 
plist-converter 0.2.0 
project-manager 3.3.6 
react 0.18.0 
regular-search 0.0.0 
relative-numbers 0.9.0 
remote-ftp 2.2.2 
rst-preview 1.3.1 
split-diff 1.5.3 
tab-numbers 0.6.1 
testing! 0.0.1-SNAPSHOT 
toggle-packages 1.1.0 
vim-mode-plus 1.36.0 
vim-mode-plus-keymaps-for-surround 0.2.1 
vimplus 0.0.0 
vis 0.0.0 
```

**Comment by emdash-ie** [comment]
(The folder `/Users/Noel/.atom/packages/ide-haskell-hie` that’s mentioned in the trace no longer exists, and hasn’t since I uninstalled the package)

**Comment by emdash-ie** [comment]
Today, the path in the error messages changed to the package `ide-python`, which I suspect the errors may have been coming from all along, caused by `pyls-mypy`, as described in [this ide-python issue](https://github.com/lgeiger/ide-python/issues/106) and [this pyls-mypy issue](https://github.com/tomv564/pyls-mypy/issues/19).

I’m closing this issue, as I don’t *think* this error was ever caused by ide-haskell-hie (though I’m not certain).

**Comment by Tehnix** [comment]
@undergroundquizscene I'm so sorry for the lack of activity on this issue! I'm glad you seem to have found what might be the root cause :) Thanks for taking the time to dig into this on your own!

**Comment by emdash-ie** [comment]
@Tehnix Don’t worry about it! There isn’t time to get to everything, you know?
