### ISSUE TITLE
HIE not working on Windows

### ISSUE THREAD

**Issue by freeman42x** [Tehnix/ide-haskell-hie#38]
There are no error messages displayed anywhere.
This is the same issue as in Visual Studio Code extension: https://github.com/alanz/vscode-hie-server/issues/124
It probably has the same cause: at some point HIE stopped talking to the clients.
The only fix that worked for me for both Atom and VS Code was to use an old version of HIE as mentioned here: https://github.com/alanz/vscode-hie-server/issues/124#issuecomment-452953041

**Comment by Tehnix** [comment]
There's not much I can do on the extension-side of things when HIE breaks, so I'll close this :)
