### ISSUE TITLE
Go to declaration

### ISSUE THREAD

**Issue by falsandtru** [Tehnix/ide-haskell-hie#4]
Will you implement "Go to declaration" feature? I couldn't find your plan about that on README.

**Comment by Tehnix** [comment]
Hmm, it's not quite clear to me what is going wrong with the hyperlink go to def, but I'll take a look at it :)

**Comment by falsandtru** [comment]
Sorry for my sorry English. You've written a plan on README as follows:

> ## Not implemented
> Find references (not implemented)

Could you update this plan as follows?

> ## Not implemented
> Go to declaration (not implemented)
> Find references (not implemented)

**Comment by Tehnix** [comment]
So, I just took another look at it, and updated HIE to the latest. Go to declaration indeed works, so I'll close this issue. Notably it's not the "Go to declaration" in the context menu (don't know where that comes from), but via the hyperlink functionality, which is `CMD + click` on macOS.

Let me know if it works, and if you have any issues, try rebuilding your project, hie is a bit brittle sometimes :/

**Comment by Tehnix** [comment]
Also, I've added some specific information in the README https://github.com/Tehnix/ide-haskell-hie#not-implemented for the things not yet implemented.

**Comment by falsandtru** [comment]
`CMD + click` works well, thanks! However, it doesn't work from the context menu.

**Comment by Tehnix** [comment]
Yeah, I was honestly a bit unsure where that came from, since it didn't fire any LSP events at all 🤔

It seems to rely on symbols having being generated, and appears to have nothing to do with LSP (just a regular Atom feature). You can check out https://github.com/atom/symbols-view/issues/9, and also you might get it to work with [ide-haskell-hasktags](https://atom.io/packages/ide-haskell-hasktags).

**Comment by falsandtru** [comment]
I see, thanks for your kindness. I'll use `CMD + click`.

**Comment by andrewufrank** [comment]
what is the command for `goto declaration` on a llinux system?

**Comment by Tehnix** [comment]
@andrewufrank If you go to `Settings -> Packages -> atom-ide-ui settings`, you can configure the keybindings under `Hyperclick`. The default for linux is `Ctrl + click`,

![screenshot 2018-04-05 11 52 00](https://user-images.githubusercontent.com/1189998/38359197-e4511b4c-38c7-11e8-806c-677cb59a8f31.png)
