### ISSUE TITLE
Got error while processing diagnostics

### ISSUE THREAD

**Issue by falsandtru** [Tehnix/ide-haskell-hie#9]
![screenshot from 2017-12-20 01-51-57](https://user-images.githubusercontent.com/3143368/34168654-68c15476-e528-11e7-8a7b-f9d4c2c5e0ae.png)

**Comment by falsandtru** [comment]
Is this not a bug of this package?

**Comment by Tehnix** [comment]
Sorry for the late reply.

Hmm, I honestly think this is an issue on HIE's side. Basically, as long as the LSP server is running and the UI is working, all operational errors are on the HIE side of things - do you get errors on other smaller projects, i.e. can HIE run?

Would it be possible for you to open an issue on https://github.com/haskell/haskell-ide-engine explaining when you run into this?

**Comment by falsandtru** [comment]
I found an issue related this problem. I'll watch it, thanks.

https://github.com/haskell/haskell-ide-engine/issues/391
